### PR TITLE
feat(mm): extend external with tags and related attributes

### PR DESCRIPTION
**Pull request by gaespa007648**
新增tags與related欄位至外部文章(External)當中，並在標籤(Tag)中新增外部文章標籤欄位。

### CODE REVIEW

**Review by erase2004 — CHANGES_REQUESTED** [review]
有欄位變動，沒有 migration SQL file
ref: https://www.prisma.io/docs/orm/prisma-migrate/workflows/data-migration#expand-your-schema-with-a-new-column

**Comment by gaespa007648** [comment]
已補上migration.sql

**Review by erase2004 — APPROVED** [review]
修改後需要確認的話，記得要按 re-request review

**Comment by gaespa007648** [comment]
ok，感謝!

**Pull request merged**
